services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app # optional for live reload during development
      - /app/node_modules
    command: npm run dev
